
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 10
  database: myapp_stats_development
  username: postgres
  password: kemtardif
 
test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 10
  database: myapp_stats_test
  username: postgres
  password: kemtardif
 
production:
  adapter: postgresql
  encoding: utf8
  pool: 10
  database: myapp_stats_production
  username: postgres
  password: kemtardif